export const WEATHER_DATA_FETCH_SUCCESS = "WEATHER_DATA_FETCH_SUCESS";
export const WEATHER_DATA_HAS_ERRORED = "WEATHER_DATA_HAS_ERRORED";
export const WEATHER_DATA_IS_LOADING = "WEATHER_DATA_IS_LOADING";
